version: '3.2'

services:
  api:
    build: .
    command: npm run start:watch
    environment:
      SERVER_PORT: '8080'
      DB_HOST: 'database'
      DB_PORT: '3306'
      DB_USER: '${DB_USER}'
      DB_NAME: '${DB_NAME}'
      DB_PASS: '${DB_PASS}'
    ports:
      - '8080:8080'
    volumes:
      - ./src:/src
      - ./nodemon.json:/nodemon.json
      - ./node_modules:/node_modules
      - ./tsconfig.json:/tsconfig.json
    depends_on:
      - migrator
    networks:
      - mysql
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    logging:
      driver: none
    environment:
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASS}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_ROOT_PASSWORD: '${DB_PASS}'
    ports:
      - '${DB_PORT}:3306'
    networks:
      - mysql
  migrator:
    build: .
    command: npm run migrate:run
    environment:
      DB_HOST: 'database'
      DB_PORT: '3306'
      DB_USER: '${DB_USER}'
      DB_NAME: '${DB_NAME}'
      DB_PASS: '${DB_PASS}'
    volumes:
      - ./src:/src
      - ./migrations:/migrations
      - ./node_modules:/node_modules
      - ./tsconfig.json:/tsconfig.json
    depends_on:
      - database
    networks:
      - mysql

networks:
  mysql:
    driver: bridge
